BEGIN TRANSACTION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'template_constraint' AND COLUMN_NAME = 'category')
BEGIN
	ALTER TABLE dbo.template_constraint ADD category nvarchar(255) NULL
END

COMMIT TRANSACTION