IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'group' AND COLUMN_NAME = 'description')
BEGIN
	ALTER TABLE dbo.[group] ADD description ntext NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'group' AND COLUMN_NAME = 'disclaimer')
BEGIN
	ALTER TABLE dbo.[group] ADD disclaimer ntext NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'group' AND COLUMN_NAME = 'isOpen')
BEGIN
	ALTER TABLE dbo.[group] ADD isOpen bit NOT NULL CONSTRAINT DF_group_isOpen DEFAULT 0
END