IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'user' AND COLUMN_NAME = 'organizationId')
BEGIN
	ALTER TABLE dbo.[user] DROP CONSTRAINT FK_user_organization
	ALTER TABLE dbo.[user] DROP COLUMN organizationId
END