//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trifolia.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrifoliaLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrifoliaLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trifolia.Web.App_GlobalResources.TrifoliaLang", typeof(TrifoliaLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and/or password are incorrect..
        /// </summary>
        public static string AuthenticationInvalid {
            get {
                return ResourceManager.GetString("AuthenticationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a StructureDefinition that already has an id.
        /// </summary>
        public static string CreateFHIR2TemplateFailedDuplicateId {
            get {
                return ResourceManager.GetString("CreateFHIR2TemplateFailedDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving your changes, please submit a support ticket!.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search requested includes sub-object criteria which is not yet supported by Trifolia.
        /// </summary>
        public static string FHIRSearchCriteriaNotSupported {
            get {
                return ResourceManager.GetString("FHIRSearchCriteriaNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to login as HL7 user.
        /// </summary>
        public static string HL7AttemptInvalid {
            get {
                return ResourceManager.GetString("HL7AttemptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to login took longer than 5 minutes to reach the server. Failed to login..
        /// </summary>
        public static string HL7AuthTimeout {
            get {
                return ResourceManager.GetString("HL7AuthTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is used to create many wonderful things, it can even be used to take over the world, so be cautious!.
        /// </summary>
        public static string PageIntro {
            get {
                return ResourceManager.GetString("PageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our First Localized Page.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A StructureDefinition with the same url already exists. To update, use PUT..
        /// </summary>
        public static string StructureDefinitionSameUrlExists {
            get {
                return ResourceManager.GetString("StructureDefinitionSameUrlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child Primitive.
        /// </summary>
        public static string TemplateEditorAddChildPrimitiveTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorAddChildPrimitiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Top-level Primitive.
        /// </summary>
        public static string TemplateEditorAddTopLevelPrimitiveTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorAddTopLevelPrimitiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates where in the base standard/schema this template/profile can be used. This field is defaulted based on the template/profile type selected, but can be customized by clicking the \&apos;...\&apos; button to the right..
        /// </summary>
        public static string TemplateEditorAppliesToTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorAppliesToTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short id is used during the export of a MS Word document and as the id field in FHIR&apos;s StructureDefinition resources. The short id must be unique in the implentation guide, and not contain any special characters (including spaces, with the exception of underscores). The short id may not be greater than 40 characters (due to MS Word\&apos;s limitation in bookmark size)..
        /// </summary>
        public static string TemplateEditorBookmarkTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorBookmarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI.
        /// </summary>
        public static string TemplateEditorBranchIdentifierHeading {
            get {
                return ResourceManager.GetString("TemplateEditorBranchIdentifierHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch/slice identifier/descriminator?.
        /// </summary>
        public static string TemplateEditorBranchIdentifierHeadingTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorBranchIdentifierHeadingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier/Discriminator.
        /// </summary>
        public static string TemplateEditorBranchIdentifierOption {
            get {
                return ResourceManager.GetString("TemplateEditorBranchIdentifierOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch/Slice.
        /// </summary>
        public static string TemplateEditorBranchingTitle {
            get {
                return ResourceManager.GetString("TemplateEditorBranchingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR.
        /// </summary>
        public static string TemplateEditorBranchRootHeading {
            get {
                return ResourceManager.GetString("TemplateEditorBranchRootHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch/slice root?.
        /// </summary>
        public static string TemplateEditorBranchRootHeadingTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorBranchRootHeadingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string TemplateEditorBranchRootOption {
            get {
                return ResourceManager.GetString("TemplateEditorBranchRootOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card..
        /// </summary>
        public static string TemplateEditorCardinalityHeading {
            get {
                return ResourceManager.GetString("TemplateEditorCardinalityHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinality.
        /// </summary>
        public static string TemplateEditorCardinalityHeadingTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorCardinalityHeadingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformance.
        /// </summary>
        public static string TemplateEditorConformanceHeadingTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConformanceHeadingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Generate:.
        /// </summary>
        public static string TemplateEditorConstraintEditorAutoGenerate {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorAutoGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding:.
        /// </summary>
        public static string TemplateEditorConstraintEditorBinding {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Date:.
        /// </summary>
        public static string TemplateEditorConstraintEditorBindingDate {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorBindingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the pre-defined binding types from the drop-down to show the fields applicable. This field is not the same as the &quot;Binding&quot; (ie: STATIC vs. DYNAMIC)..
        /// </summary>
        public static string TemplateEditorConstraintEditorBindingTypeTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorBindingTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string TemplateEditorConstraintEditorCode {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code System:.
        /// </summary>
        public static string TemplateEditorConstraintEditorCodeSystem {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorCodeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consult the help documentation&apos;s &quot;CDA Best Practices&quot; section for information on how to require a single value binding on a MAY attribute..
        /// </summary>
        public static string TemplateEditorConstraintEditorCodeTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformance:.
        /// </summary>
        public static string TemplateEditorConstraintEditorConformance {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorConformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conf/Card:.
        /// </summary>
        public static string TemplateEditorConstraintEditorConformanceCardinality {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorConformanceCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type:.
        /// </summary>
        public static string TemplateEditorConstraintEditorDataType {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options in the &quot;Data Type&quot; drop-down include derived types from the base data type allowed in the standard. Selecting a non-default data type will make different child nodes available to constrain..
        /// </summary>
        public static string TemplateEditorConstraintEditorDataTypeTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorDataTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string TemplateEditorConstraintEditorDescription {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported before constraint.
        /// </summary>
        public static string TemplateEditorConstraintEditorDescriptionTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorDescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritable:.
        /// </summary>
        public static string TemplateEditorConstraintEditorInheritable {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorInheritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to single-value bindings. When checked, value must be exactly this. When not checked, value must have at least these property values.
        /// </summary>
        public static string TemplateEditorConstraintEditorIsFixedTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorIsFixedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this modifies the meaning of other elements.
        /// </summary>
        public static string TemplateEditorConstraintEditorIsModifierTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorIsModifierTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label:.
        /// </summary>
        public static string TemplateEditorConstraintEditorLabel {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported at end of constraint.
        /// </summary>
        public static string TemplateEditorConstraintEditorLabelTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the element must be supported.
        /// </summary>
        public static string TemplateEditorConstraintEditorMustSupportTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorMustSupportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooted:.
        /// </summary>
        public static string TemplateEditorConstraintEditorRooted {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Conf.:.
        /// </summary>
        public static string TemplateEditorConstraintEditorValueConformance {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintEditorValueConformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformance Number.
        /// </summary>
        public static string TemplateEditorConstraintNumberHeadingTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorConstraintNumberHeadingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string TemplateEditorContextHeading {
            get {
                return ResourceManager.GetString("TemplateEditorContextHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Computable.
        /// </summary>
        public static string TemplateEditorCreateComputableTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorCreateComputableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string TemplateEditorDataTypeHeading {
            get {
                return ResourceManager.GetString("TemplateEditorDataTypeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string TemplateEditorDuplicateTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorDuplicateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        public static string TemplateEditorEditNoteTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorEditNoteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize/maximize constraint editor.
        /// </summary>
        public static string TemplateEditorExpandCollapseConstraintEditorTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorExpandCollapseConstraintEditorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if instances of the template/profile can have additional information (open), or if it can only contain explicitly what is defined in the template/profile (closed)..
        /// </summary>
        public static string TemplateEditorExtensibilityTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorExtensibilityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the implementation guide that the template/profile belongs to. The template/profile may still be referenced by other implementation guides (via contained or implied relationships)..
        /// </summary>
        public static string TemplateEditorImplementationGuideTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorImplementationGuideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies To:.
        /// </summary>
        public static string TemplateEditorMetaDataAppliesToField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataAppliesToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authored By:.
        /// </summary>
        public static string TemplateEditorMetaDataAuthoredByField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataAuthoredByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Id:.
        /// </summary>
        public static string TemplateEditorMetaDataBookmarkField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataBookmarkField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TemplateEditorMetaDataDescriptionField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataDescriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensibility:.
        /// </summary>
        public static string TemplateEditorMetaDataExtensibilityField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataExtensibilityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Guide:.
        /// </summary>
        public static string TemplateEditorMetaDataImplementationGuideField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataImplementationGuideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string TemplateEditorMetaDataNameField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of:.
        /// </summary>
        public static string TemplateEditorMetaDataNewVersionOfField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataNewVersionOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TemplateEditorMetaDataNotesField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataNotesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Id:.
        /// </summary>
        public static string TemplateEditorMetaDataOidField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataOidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization:.
        /// </summary>
        public static string TemplateEditorMetaDataOrganizationField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataOrganizationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string TemplateEditorMetaDataStatusField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataStatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TemplateEditorMetaDataTemplateTypeField {
            get {
                return ResourceManager.GetString("TemplateEditorMetaDataTemplateTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes are only available for review by template/profile authors (they are not included in exports)..
        /// </summary>
        public static string TemplateEditorNotesTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorNotesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique identifier for the template/profile. Must be less than 255 characters. For FHIR, this identifier is used as the URL of the StructureDefinition resource and is best practice to use the implementation guide&apos;s base url with the short id..
        /// </summary>
        public static string TemplateEditorOidTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorOidTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TemplateEditorRemoveTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorRemoveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the tree for a constraint by number. Press enter to search..
        /// </summary>
        public static string TemplateEditorSearchConstraintTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorSearchConstraintTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the type of template/profile (typically document vs. section vs. entry). The templates/profiles are organized by the template/profile type when exporting as an MS Word document. Pre-determined defaults are specified for the Applies To field when selecting a template/profile type..
        /// </summary>
        public static string TemplateEditorTemplateTypeTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorTemplateTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string TemplateEditorValidationErrors {
            get {
                return ResourceManager.GetString("TemplateEditorValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no validation errors/warnings..
        /// </summary>
        public static string TemplateEditorValidationNoMessages {
            get {
                return ResourceManager.GetString("TemplateEditorValidationNoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string TemplateEditorValidationWarnings {
            get {
                return ResourceManager.GetString("TemplateEditorValidationWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View mode changes between the Analyst, Editor and Engineer screens of the constraint editor..
        /// </summary>
        public static string TemplateEditorViewModeTooltip {
            get {
                return ResourceManager.GetString("TemplateEditorViewModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to modify this template..
        /// </summary>
        public static string TemplateEditPermissionMessage {
            get {
                return ResourceManager.GetString("TemplateEditPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a FHIR DSTU2 profile.
        /// </summary>
        public static string TemplateNotFHIRDSTU2 {
            get {
                return ResourceManager.GetString("TemplateNotFHIRDSTU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a FHIR STU3 profile!.
        /// </summary>
        public static string TemplateNotFHIRSTU3 {
            get {
                return ResourceManager.GetString("TemplateNotFHIRSTU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the template/profile requested: {0}.
        /// </summary>
        public static string TemplateNotFoundMessageFormat {
            get {
                return ResourceManager.GetString("TemplateNotFoundMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this template..
        /// </summary>
        public static string TemplateViewPermissionMessage {
            get {
                return ResourceManager.GetString("TemplateViewPermissionMessage", resourceCulture);
            }
        }
    }
}
