IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DatabaseVersion')
BEGIN
	DROP TABLE DatabaseVersion
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'codevalidation_map')
BEGIN
	DROP TABLE codevalidation_map
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'codevalidation')
BEGIN
	DROP TABLE codevalidation
END
GO