BEGIN TRANSACTION

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'implementationguide_file' AND COLUMN_NAME = 'url')
BEGIN
	ALTER TABLE dbo.implementationguide_file ADD url nvarchar(255) NULL
END

COMMIT TRANSACTION