// <auto-generated />
namespace Trifolia.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addImplementationGuideIdTov_templateList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImplementationGuideIdTov_templateList));
        
        string IMigrationMetadata.Id
        {
            get { return "201803231315265_addImplementationGuideIdTov_templateList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
